version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: irtea_db
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: